
import Exercicio1.ContagemVotos;
import Exercicio2.BubbleSort;
import Exercicio3.Fatorial;
import Exercicio4.SomaMultiplos;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lrber
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtVotosValidos = new javax.swing.JTextField();
        txtVotosBrancos = new javax.swing.JTextField();
        txtVotosNulos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblTotalVotos = new javax.swing.JLabel();
        btnPercentualVotos = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnBubble = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtFatorial = new javax.swing.JTextField();
        btnFatorial = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblResultadoFatorial = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMultiplo = new javax.swing.JTextField();
        btnMultiplo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lblResultadoMultiplo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtareaPercentual = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtareaBubble = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Contagem de votos:");

        jLabel2.setText("Votos Validos:");

        jLabel3.setText("Votos Brancos:");

        jLabel4.setText("Votos Nulos:");

        txtVotosValidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVotosValidosKeyTyped(evt);
            }
        });

        txtVotosBrancos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVotosBrancosKeyTyped(evt);
            }
        });

        txtVotosNulos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVotosNulosKeyTyped(evt);
            }
        });

        jLabel5.setText("Total de Votos:");

        btnPercentualVotos.setText("Calcular Percentual de Votos");
        btnPercentualVotos.setToolTipText("");
        btnPercentualVotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPercentualVotosActionPerformed(evt);
            }
        });

        jLabel7.setText("Ordenação de vetor (bubble sort)");

        btnBubble.setText("Executar bubble");
        btnBubble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBubbleActionPerformed(evt);
            }
        });

        jLabel6.setText("Entre com um numero para calculo fatorial ! :");

        txtFatorial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFatorialKeyTyped(evt);
            }
        });

        btnFatorial.setText("Calcular");
        btnFatorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFatorialActionPerformed(evt);
            }
        });

        jLabel8.setText("Resultado: ");

        jLabel9.setText("Entre com um numero para calculo da soma dos multiplos de 3 e 5 :");

        txtMultiplo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMultiploKeyTyped(evt);
            }
        });

        btnMultiplo.setText("Calcular");
        btnMultiplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiploActionPerformed(evt);
            }
        });

        jLabel10.setText("Resultado: ");

        txtareaPercentual.setColumns(20);
        txtareaPercentual.setRows(5);
        jScrollPane3.setViewportView(txtareaPercentual);

        txtareaBubble.setColumns(20);
        txtareaBubble.setRows(5);
        jScrollPane4.setViewportView(txtareaBubble);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMultiplo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnMultiplo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblResultadoMultiplo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFatorial, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnFatorial))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblResultadoFatorial, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVotosValidos, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVotosBrancos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtVotosNulos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalVotos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPercentualVotos))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBubble))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(lblTotalVotos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtVotosValidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtVotosBrancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtVotosNulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPercentualVotos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(btnBubble))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFatorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFatorial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(lblResultadoFatorial, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMultiplo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiplo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addComponent(lblResultadoMultiplo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPercentualVotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPercentualVotosActionPerformed
        // TODO add your handling code here:
        int votos_validos, votos_brancos, votos_nulos, total_votos;
        
        votos_validos = Integer.parseInt(txtVotosValidos.getText());
        votos_brancos = Integer.parseInt(txtVotosBrancos.getText());
        votos_nulos = Integer.parseInt(txtVotosNulos.getText());
        
        total_votos = votos_validos + votos_brancos + votos_nulos;
        
        lblTotalVotos.setText(Integer.toString(total_votos));
        
        ContagemVotos contagem1 = new ContagemVotos(total_votos, votos_validos, votos_brancos, votos_nulos);
        
        txtareaPercentual.setText("Percentual de votos validos: " + Integer.toString(contagem1.totalVotosValidos()) + "%");
        txtareaPercentual.setText(txtareaPercentual.getText() + "\n" + "Percentual de votos brancos: " + Integer.toString(contagem1.totalVotosBrancos()) + "%");
        txtareaPercentual.setText(txtareaPercentual.getText() + "\n" + "Percentual de votos nulos: " + Integer.toString(contagem1.totalVotosNulos()) + "%");
    }//GEN-LAST:event_btnPercentualVotosActionPerformed

    private void txtVotosValidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVotosValidosKeyTyped
        // TODO add your handling code here:
                
        apenasNumeros(evt);
    }//GEN-LAST:event_txtVotosValidosKeyTyped

    private void txtVotosBrancosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVotosBrancosKeyTyped
        // TODO add your handling code here:
              
        apenasNumeros(evt);
        
    }//GEN-LAST:event_txtVotosBrancosKeyTyped

    private void txtVotosNulosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVotosNulosKeyTyped
        // TODO add your handling code here:
        apenasNumeros(evt);
    }//GEN-LAST:event_txtVotosNulosKeyTyped

    private void txtFatorialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFatorialKeyTyped
        // TODO add your handling code here:
        apenasNumeros(evt);
    }//GEN-LAST:event_txtFatorialKeyTyped

    private void txtMultiploKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMultiploKeyTyped
        // TODO add your handling code here:
        apenasNumeros(evt);
    }//GEN-LAST:event_txtMultiploKeyTyped

    private void btnBubbleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBubbleActionPerformed
        // TODO add your handling code here:
        
        int vetor[] = new int[10];
        txtareaBubble.setText("Vetor original: " + "\n"  + "[");
        for (int i =0; i< 10; i ++){
            vetor[i] = (int)Math.round(Math.random() * 100);
            txtareaBubble.setText(txtareaBubble.getText()+ "," + vetor[i]);
        }
        txtareaBubble.setText(txtareaBubble.getText()+ "]" + "\n");
        
        BubbleSort sort1 = new BubbleSort(vetor);
        sort1.ordenar();
        vetor = sort1.getVetor();
        
        txtareaBubble.setText(txtareaBubble.getText()+ "vetor ordenado" + "\n" + "[");
        for (int i =0; i< 10; i ++){
            txtareaBubble.setText(txtareaBubble.getText()+ "," + vetor[i]);
        }
        txtareaBubble.setText(txtareaBubble.getText()+ "]" + "\n");
    }//GEN-LAST:event_btnBubbleActionPerformed

    private void btnFatorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFatorialActionPerformed
        // TODO add your handling code here:
        
        int fatorial = Integer.parseInt(txtFatorial.getText());
        Fatorial fator = new Fatorial();
        
        lblResultadoFatorial.setText(Integer.toString(fator.calculoFatorial(fatorial)));
    }//GEN-LAST:event_btnFatorialActionPerformed

    private void btnMultiploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiploActionPerformed
        // TODO add your handling code here:
        
        int multiplo = Integer.parseInt(txtMultiplo.getText());
        SomaMultiplos soma = new SomaMultiplos();
        
        lblResultadoMultiplo.setText(Integer.toString(soma.somaMultiplos3e5(multiplo)));
    }//GEN-LAST:event_btnMultiploActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }
    
    //Evitar adição de Char ou string no campo
    private void apenasNumeros(java.awt.event.KeyEvent evt){
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBubble;
    private javax.swing.JButton btnFatorial;
    private javax.swing.JButton btnMultiplo;
    private javax.swing.JButton btnPercentualVotos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblResultadoFatorial;
    private javax.swing.JLabel lblResultadoMultiplo;
    private javax.swing.JLabel lblTotalVotos;
    private javax.swing.JTextField txtFatorial;
    private javax.swing.JTextField txtMultiplo;
    private javax.swing.JTextField txtVotosBrancos;
    private javax.swing.JTextField txtVotosNulos;
    private javax.swing.JTextField txtVotosValidos;
    private javax.swing.JTextArea txtareaBubble;
    private javax.swing.JTextArea txtareaPercentual;
    // End of variables declaration//GEN-END:variables
}
